### ISSUE TITLE
Бот еще работает?

### ISSUE THREAD

**Issue by John677** [IgorKhramtsov/SteamMultiAccount#1]
Пытался собрать вылазят ошибки, докинул библиотеки, однако вываливается сам софт.
Можешь релизнуть последнюю версию?

**Comment by IgorKhramtsov** [comment]
Залил релиз, проверяй, если будут проблемы отпишись.

**Comment by John677** [comment]
![image](https://cloud.githubusercontent.com/assets/19402400/26209245/ec0010d0-3bf4-11e7-8d66-4c1e9d4f825b.png)
Error	CS0246	The type or namespace name 'Steamworks' could not be found (are you missing a using directive or an assembly reference?)	
Error	CS0246	The type or namespace name 'HtmlAgilityPack' could not be found (are you missing a using directive or an assembly reference?)
Error	CS0246	The type or namespace name 'HtmlDocument' could not be found (are you missing a using directive or an assembly reference?)
Warning		The referenced component 'Steamworks.NET' could not be found.	

Как то так)

**Comment by IgorKhramtsov** [comment]
Проверяй опять, релиз перезалил, должно работать.

**Comment by John677** [comment]
![image](https://cloud.githubusercontent.com/assets/19402400/26214357/c0ef31fe-3c04-11e7-8f16-e3be750a6b97.png)
Так и должно быть?)

**Comment by IgorKhramtsov** [comment]
Да, пкм по левой колонке, и добавляй аккаунт.

**Comment by John677** [comment]
SteamAuthCode это shared_secret из mafile или что-то другое?

**Comment by IgorKhramtsov** [comment]
У меня есть проект 2 факторного аутентификатора, это от него. Но я еще не особо тестировал эту функцию, возможно она вообще не работает, можешь в коде глянуть.
